grafana:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.manasareddy.online

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.manasareddy.online
